
paths: ${machine.paths}

defaults:
  - _self_
  - dataset: test
  - machine: gpu
  - model: diffusion_model

train:
  seed: 42
  epochs: 100

is_val: True

logging:
  project: "GeneDiffusion"
  dir: "logs/geneset_expansion"