
hydra:
  run:
    dir: outputs/${data.data_name}/${model.model_name}
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

defaults:
  - _self_
  - data: test
  - machine: gpu
  - model: diffusion_model_large
  - optimizer: adamw
  - scheduler: cosine

train:
  seed: 42
  max_epochs: 40

is_val: True

log:
  log_interval: 100