
defaults:
  - _self_
  - data: test
  - machine: gpu
  - model: diffusion_model
  - optimizer: adamw
  - scheduler: cosine

train:
  seed: 42
  max_epochs: 100

is_val: True

log:
  log_interval: 30
  project: "GeneDiffusion"
  dir: "logs/geneset_expansion"