
hydra:
  run:
    dir: results/${data.data_name}/${model.model_name}
  job: # automatically go to the job folder (needed for hydra > 1.2 with new behavior)
    chdir: true

defaults:
  - _self_
  - data: train10m
  - machine: gpu
  - model: manifold_diffusion_model_norm
  - optimizer: adamw
  - scheduler: cosine
  - test: test7

train:
  seed: 42
  max_epochs: 5
  resume: True
  resume_epoch: 0

test:
  seed: 42
  epoch: 4
  result_path: ${test.data_name}
  solver: manifold_ddim


is_val: False

log:
  log_interval: 100